1.3.0
Change-Id: I06d91da0a7baf244d94d7f2b59ab028954d776e3

diff --git a/assets/home/bin/linuxdeploy b/assets/home/bin/linuxdeploy
--- a/assets/home/bin/linuxdeploy
+++ b/assets/home/bin/linuxdeploy
@@ -32,6 +32,12 @@ install_system()
 	fi
 
 	echo "[PRINT_LN] Selected distribution: $DISTRIB"
+	case "$DISTRIB" in
+	BackTrack)
+		echo "[PRINT_LN] This distribution does not support network installation!"
+		return 1
+	;;
+	esac
 
 	echo "[PRINT] Checking destination path ... "
 	if [ "$DEPLOY_TYPE" == "image" ]; then
@@ -54,13 +60,22 @@ install_system()
 	if [ "$DEPLOY_TYPE" == "image" ]; then
 		echo "[PRINT] Making new disk image ($IMG_SIZE MB) ... "
 		(set -e
+		    if [ "$IMG_SIZE" -eq 0 ]; then
+		    	[ -f "$IMG_TARGET" ] && FILE_SIZE=`stat -c %s $IMG_TARGET` || FILE_SIZE=0
+		    	DIR_NAME=`dirname $IMG_TARGET`
+		    	BLOCK_SIZE=`stat -c %s -f $DIR_NAME`
+				AVAILABLE_SIZE=`stat -c %a -f $DIR_NAME`
+				let AVAILABLE_SIZE="($BLOCK_SIZE*$AVAILABLE_SIZE)+$FILE_SIZE"
+				let IMG_SIZE="($AVAILABLE_SIZE-$AVAILABLE_SIZE/10)/1048576"
+				[ "$IMG_SIZE" -gt 4095 ] && IMG_SIZE=4095
+			fi
 			if [ "$IMG_SIZE" -ge 2048 ]; then
 				DD_SEEK=2047
 				let DD_COUNT=$IMG_SIZE-2047
 			else
 				DD_SEEK=$IMG_SIZE
 				DD_COUNT=0
-			fi 
+			fi
 			dd if=/dev/zero of=$IMG_TARGET bs=1048576 seek=$DD_SEEK count=$DD_COUNT
 		exit 0)
 		if [ $? -eq 0 ]; then
@@ -130,29 +145,29 @@ configure_system()
 	echo "[PRINT_LN] Configuring Linux system: "
 	
 	echo "[PRINT] APT ... "
-	case "$DISTRIB" in
-	Debian)
-		(set -e
-			[ -e "$MNT_TARGET/etc/apt/sources.list" ] && cp $MNT_TARGET/etc/apt/sources.list $MNT_TARGET/etc/apt/sources.list.bak
-			echo "deb $MIRROR $SUITE main contrib non-free" > $MNT_TARGET/etc/apt/sources.list
+	(set -e
+		[ -e "$MNT_TARGET/etc/apt/sources.list" ] && cp $MNT_TARGET/etc/apt/sources.list $MNT_TARGET/etc/apt/sources.list.bak
+		echo "# Generated by Linux Deploy" > $MNT_TARGET/etc/apt/sources.list
+		case "$DISTRIB" in
+		Debian)
+			echo "deb $MIRROR $SUITE main contrib non-free" >> $MNT_TARGET/etc/apt/sources.list
 			echo "deb-src $MIRROR $SUITE main contrib non-free" >> $MNT_TARGET/etc/apt/sources.list
-			chmod 644 $MNT_TARGET/etc/apt/sources.list
-		exit 0)
-		[ $? -eq 0 ] && echo "[RESULT_LN] done" || echo "[RESULT_LN] fail"
-	;;
-	Ubuntu)
-		(set -e
-			[ -e "$MNT_TARGET/etc/apt/sources.list" ] && cp $MNT_TARGET/etc/apt/sources.list $MNT_TARGET/etc/apt/sources.list.bak
-			echo "deb $MIRROR $SUITE main universe multiverse" > $MNT_TARGET/etc/apt/sources.list
+		;;
+		Ubuntu)
+			echo "deb $MIRROR $SUITE main universe multiverse" >> $MNT_TARGET/etc/apt/sources.list
 			echo "deb-src $MIRROR $SUITE main universe multiverse" >> $MNT_TARGET/etc/apt/sources.list
-			chmod 644 $MNT_TARGET/etc/apt/sources.list
-		exit 0)
-		[ $? -eq 0 ] && echo "[RESULT_LN] done" || echo "[RESULT_LN] fail"
-	;;
-	*)
-		echo "[RESULT_LN] skip"
-	;;
-	esac
+		;;
+		BackTrack)
+			echo "deb $MIRROR $SUITE main universe multiverse" >> $MNT_TARGET/etc/apt/sources.list
+			echo "deb-src $MIRROR $SUITE main universe multiverse" >> $MNT_TARGET/etc/apt/sources.list
+			echo "deb http://all.repository.backtrack-linux.org revolution main microverse non-free testing" >> $MNT_TARGET/etc/apt/sources.list
+			echo "deb http://source.repository.backtrack-linux.org revolution main microverse non-free testing" >> $MNT_TARGET/etc/apt/sources.list
+			echo "deb http://armel.repository.backtrack-linux.org revolution main microverse non-free testing" >> $MNT_TARGET/etc/apt/sources.list
+		;;
+		esac
+		chmod 644 $MNT_TARGET/etc/apt/sources.list
+	exit 0)
+	[ $? -eq 0 ] && echo "[RESULT_LN] done" || echo "[RESULT_LN] fail"
 
 	echo "[PRINT] hosts ... "
 	(set -e
@@ -259,49 +274,46 @@ configure_system()
 		PROFILE_STR='PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
 		is_str=`cat $MNT_TARGET$USER_HOME/.profile | grep "$PROFILE_STR" || true`
 		[ -z "$is_str" ] && echo $PROFILE_STR >> $MNT_TARGET$USER_HOME/.profile
-		is_gui=`echo $INSTALL_GUI | grep -i "^y" || true`
-		if [ -n "$is_gui" ]; then
-			mkdir $MNT_TARGET$USER_HOME/.vnc || true
-			chmod 755 $MNT_TARGET$USER_HOME/.vnc
-			echo "MPTcXfgXGiY=" | base64 -d > $MNT_TARGET$USER_HOME/.vnc/passwd
-			chmod 600 $MNT_TARGET$USER_HOME/.vnc/passwd
-			echo 'XAUTHORITY=$HOME/.Xauthority' > $MNT_TARGET$USER_HOME/.vnc/xstartup
-			echo 'export XAUTHORITY' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-			case "$DESKTOP_ENV" in
-			XTerm)
-				echo 'xterm -max &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-			;;
-			LXDE)
-				echo 'startlxde &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-			;;
-			Xfce)
-				echo 'startxfce4 &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-			;;
-			GNOME)
-				echo 'XKL_XMODMAP_DISABLE=1' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-				echo 'export XKL_XMODMAP_DISABLE' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-				echo 'SESSION_SUPPORT=`gnome-session -h | grep "\-\-session"`' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-				echo 'if [ -n "$SESSION_SUPPORT" ]; then' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-				echo 'gnome-session --session=gnome &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-				echo 'else' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-				echo 'gnome-session &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-				echo 'fi' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-			;;
-			Unity)
-				echo 'gnome-session --session=ubuntu-2d &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-			;;
-			KDE)
-				echo 'startkde &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
-			;;
-			*)
-				echo "$DESKTOP_ENV not found!"
-			;;
-			esac
-			chmod 755 $MNT_TARGET$USER_HOME/.vnc/xstartup
-			echo "#!/bin/sh" > $MNT_TARGET$USER_HOME/.xsession
-			cat $MNT_TARGET$USER_HOME/.vnc/xstartup >> $MNT_TARGET$USER_HOME/.xsession
-			chmod 755 $MNT_TARGET$USER_HOME/.xsession
-		fi
+		mkdir $MNT_TARGET$USER_HOME/.vnc || true
+		chmod 755 $MNT_TARGET$USER_HOME/.vnc
+		echo "MPTcXfgXGiY=" | base64 -d > $MNT_TARGET$USER_HOME/.vnc/passwd
+		chmod 600 $MNT_TARGET$USER_HOME/.vnc/passwd
+		echo 'XAUTHORITY=$HOME/.Xauthority' > $MNT_TARGET$USER_HOME/.vnc/xstartup
+		echo 'export XAUTHORITY' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+		case "$DESKTOP_ENV" in
+		XTerm)
+			echo 'xterm -max &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+		;;
+		LXDE)
+			echo 'startlxde &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+		;;
+		Xfce)
+			echo 'startxfce4 &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+		;;
+		GNOME)
+			echo 'XKL_XMODMAP_DISABLE=1' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+			echo 'export XKL_XMODMAP_DISABLE' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+			echo 'SESSION_SUPPORT=`gnome-session -h | grep "\-\-session"`' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+			echo 'if [ -n "$SESSION_SUPPORT" ]; then' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+			echo 'gnome-session --session=gnome &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+			echo 'else' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+			echo 'gnome-session &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+			echo 'fi' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+		;;
+		Unity)
+			echo 'gnome-session --session=ubuntu-2d &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+		;;
+		KDE)
+			echo 'startkde &' >> $MNT_TARGET$USER_HOME/.vnc/xstartup
+		;;
+		*)
+			echo "$DESKTOP_ENV not found!"
+		;;
+		esac
+		chmod 755 $MNT_TARGET$USER_HOME/.vnc/xstartup
+		echo "#!/bin/sh" > $MNT_TARGET$USER_HOME/.xsession
+		cat $MNT_TARGET$USER_HOME/.vnc/xstartup >> $MNT_TARGET$USER_HOME/.xsession
+		chmod 755 $MNT_TARGET$USER_HOME/.xsession
 		chown -R $USER_ID:$GROUP_ID $MNT_TARGET$USER_HOME
 	exit 0)
 	[ $? -eq 0 ] && echo "[RESULT_LN] done" || echo "[RESULT_LN] fail"
